languages:
  JavaScri pt: true
engines:
  eslint:
    enabled: true
ratings:
   paths:
   - src/**
exclude_paths:
- dist/**/*
- docs/**/*
- jspm_packages/**/*
- node_modules/**/*
- config.js
- gulpfile.js